export const cardArr = [
	{
		id: 0,
		img: '/img/card-img.jpeg',
		title: 'Первый товар',
		price: '170 ₽',
		adress: 'Казань, р-н Вахитовский',
		date: '10 июля 11:39',
		description: 'Продаю не спеша самокат в хорошем состоянии.',
	},
	{
		id: 1,
		img: '/img/card-img.jpeg',
		title: 'Второй товар',
		price: '171 ₽',
		adress: 'Казань, р-н Вахитовский',
		date: '10 июля 11:39',
		description: 'Продаю не спеша самокат в хорошем состоянии.',
	},
	{
		id: 2,
		img: '/img/card-img.jpeg',
		title: 'Третий товар',
		price: '172 ₽',
		adress: 'Казань, р-н Вахитовский',
		date: '10 июля 11:39',
		description: 'Продаю не спеша самокат в хорошем состоянии.',
	},
	{
		id: 3,
		img: '/img/card-img.jpeg',
		title: 'Четвертый товар',
		price: '173 ₽',
		adress: 'Казань, р-н Вахитовский',
		date: '10 июля 11:39',
		description: 'Продаю не спеша самокат в хорошем состоянии.',
	},
	{
		id: 4,
		img: '/img/card-img.jpeg',
		title: 'Пятый товар',
		price: '174 ₽',
		adress: 'Казань, р-н Вахитовский',
		date: '10 июля 11:39',
		description: 'Продаю не спеша самокат в хорошем состоянии.',
	},
	{
		id: 5,
		img: '/img/card-img.jpeg',
		title: 'Шестой товар',
		price: '175 ₽',
		adress: 'Казань, р-н Вахитовский',
		date: '10 июля 11:39',
		description: 'Продаю не спеша самокат в хорошем состоянии.',
	},
];

export const services = [
	{
		id: 0,
		img: '/img/van.svg',
		alt: 'van',
		title: 'Доставка',
		text: 'Проверка при получении и возможность бесплатно вернуть товар',
		lower: false,
	},
	{
		id: 1,
		img: '/img/sedan.svg',
		alt: 'sedan',
		title: 'Автотека',
		text: 'Отчёт с историей авто: пробег, владельцы, сведения о залоге, ДТП и ремонтах',
		lower: false,
	},
	{
		id: 2,
		img: '/img/love.svg',
		alt: 'love',
		title: 'Онлайн-бронирование жилья',
		text: 'Посуточная аренда квартир и домов: большой выбор вариантов для поездок по России',
		lower: true,
	},
]